/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Artwork } from "./Artwork";
import { ArtworkCountArgs } from "./ArtworkCountArgs";
import { ArtworkFindManyArgs } from "./ArtworkFindManyArgs";
import { ArtworkFindUniqueArgs } from "./ArtworkFindUniqueArgs";
import { DeleteArtworkArgs } from "./DeleteArtworkArgs";
import { ArtworkService } from "../artwork.service";
@graphql.Resolver(() => Artwork)
export class ArtworkResolverBase {
  constructor(protected readonly service: ArtworkService) {}

  async _artworksMeta(
    @graphql.Args() args: ArtworkCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Artwork])
  async artworks(
    @graphql.Args() args: ArtworkFindManyArgs
  ): Promise<Artwork[]> {
    return this.service.artworks(args);
  }

  @graphql.Query(() => Artwork, { nullable: true })
  async artwork(
    @graphql.Args() args: ArtworkFindUniqueArgs
  ): Promise<Artwork | null> {
    const result = await this.service.artwork(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Artwork)
  async deleteArtwork(
    @graphql.Args() args: DeleteArtworkArgs
  ): Promise<Artwork | null> {
    try {
      return await this.service.deleteArtwork(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
