/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ArtistProfile } from "./ArtistProfile";
import { ArtistProfileCountArgs } from "./ArtistProfileCountArgs";
import { ArtistProfileFindManyArgs } from "./ArtistProfileFindManyArgs";
import { ArtistProfileFindUniqueArgs } from "./ArtistProfileFindUniqueArgs";
import { DeleteArtistProfileArgs } from "./DeleteArtistProfileArgs";
import { ArtistProfileService } from "../artistProfile.service";
@graphql.Resolver(() => ArtistProfile)
export class ArtistProfileResolverBase {
  constructor(protected readonly service: ArtistProfileService) {}

  async _artistProfilesMeta(
    @graphql.Args() args: ArtistProfileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ArtistProfile])
  async artistProfiles(
    @graphql.Args() args: ArtistProfileFindManyArgs
  ): Promise<ArtistProfile[]> {
    return this.service.artistProfiles(args);
  }

  @graphql.Query(() => ArtistProfile, { nullable: true })
  async artistProfile(
    @graphql.Args() args: ArtistProfileFindUniqueArgs
  ): Promise<ArtistProfile | null> {
    const result = await this.service.artistProfile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ArtistProfile)
  async deleteArtistProfile(
    @graphql.Args() args: DeleteArtistProfileArgs
  ): Promise<ArtistProfile | null> {
    try {
      return await this.service.deleteArtistProfile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
