/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ArtCategory } from "./ArtCategory";
import { ArtCategoryCountArgs } from "./ArtCategoryCountArgs";
import { ArtCategoryFindManyArgs } from "./ArtCategoryFindManyArgs";
import { ArtCategoryFindUniqueArgs } from "./ArtCategoryFindUniqueArgs";
import { DeleteArtCategoryArgs } from "./DeleteArtCategoryArgs";
import { ArtCategoryService } from "../artCategory.service";
@graphql.Resolver(() => ArtCategory)
export class ArtCategoryResolverBase {
  constructor(protected readonly service: ArtCategoryService) {}

  async _artCategoriesMeta(
    @graphql.Args() args: ArtCategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ArtCategory])
  async artCategories(
    @graphql.Args() args: ArtCategoryFindManyArgs
  ): Promise<ArtCategory[]> {
    return this.service.artCategories(args);
  }

  @graphql.Query(() => ArtCategory, { nullable: true })
  async artCategory(
    @graphql.Args() args: ArtCategoryFindUniqueArgs
  ): Promise<ArtCategory | null> {
    const result = await this.service.artCategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ArtCategory)
  async deleteArtCategory(
    @graphql.Args() args: DeleteArtCategoryArgs
  ): Promise<ArtCategory | null> {
    try {
      return await this.service.deleteArtCategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
